### ISSUE TITLE
v1.0.0.0 planning

### ISSUE THREAD

**Issue by bergmark** [bos/aeson#392]
in suggested merge order:
- [x] #300 via #307 Removing contents field for nullary constructors
- [x] Investigate whether #307 is/can be made a non-breaking change (no since the encode output changes, but `"contents" : []` is luckily still accepted when parsing)
- [x] #366 Fix a bug with generics and single-field records
- [x] #352 via #381 Lifted type classes
- [x] #351 via #382 stop using overlapping instances for strings
- [x] #289 via #341 Generalized map serialization
- [x] #391 Modify higher kinded typeclasses from #381
- [x] #387 Fix omitNothingFields + genericToEncoding via #394
- [x] #357 JSONPath isn't tracked in autoderived instances (TH & generics) via #398
- [x] #375 Improve haddocks by not using orphan instances
- [x] Generics for Higher kinded type classes via #414 and #415
- [x] Add documentation on how to use/write `ToJSONKey` (etc) instances. @andrewthad
- [x] Finalise encoding refactoring @phadej
- [x] Add notes on all these checklist items to the changelog @bergmark
- [x] Write tests for lifted typeclasses and their generic/th derivations @phadej
- [x] Do some stackage/Silk testing @bergmark
- [x] Fix recently added TODOs
- [x] #317 Do not accept and truncate floats to integrals

Please give feedback if I missed something!

**Comment by bergmark** [comment]
@andrewthad @phadej should we start by merge the lifted type classes next?

**Comment by andrewthad** [comment]
Yeah, I think that that one is the best place to start since  it was rebased on top of master like a week ago.

**Comment by RyanGlScott** [comment]
We should probably add generics/TH support for the lifted typeclasses to this list. I haven't made an issue for it, since I was hoping it could be a part of #352, but I dropped the ball.

**Comment by andrewthad** [comment]
@RyanGlScott If I understand correctly, the generics/TH support is a non-breaking change. Even if it were added after the `0.12` release, I think it would only require bumping minor version. If it's something that you can do in under a week, I don't think that anyone would object to you adding it for the `0.12` release though.

**Comment by andrewthad** [comment]
Also @bergmark, I'd still like to redo the module merge from https://github.com/bos/aeson/issues/375 to eliminate orphan instances. I think that now is probably a good time to do that. Let me know if you agree and I'll do it.

**Comment by andrewthad** [comment]
Nevermind, I just noticed https://github.com/bos/aeson/pull/412

**Comment by andrewthad** [comment]
Down to one final checkbox. I'll add the docs for using `ToJSONKey` and friends.

**Comment by bergmark** [comment]
before i added another one ;-)  But thanks!

I'll do the changelog later.

**Comment by phadej** [comment]
I'd like to finalise my `Encoding` related refactoring and write tests to lifted typeclasses and their generic/th derivations

**Comment by phadej** [comment]
Few more points:

write Key instance to at least numeric and datetime types, then the ones I'd personally need would be covered. I can do it while making `Encoding` related refactorings, as they would be easy to add next to `ToJSON` and `FromJSON` instances.

I'd like to see what needed to be exported to write instance for [`InsOrdHashMap`](http://hackage.haskell.org/package/insert-ordered-containers-0.1.0.1/docs/Data-HashMap-Strict-InsOrd.html) using new aeson's `ToJSONKey` and `FromJSONKey` functionality

**Comment by bergmark** [comment]
@andrewthad Did you consider error messages for `FromJSONKey`? I suppose this wasn't needed before. It would be super nice if we had JSONPath error messages here as well

**Comment by andrewthad** [comment]
I hadn't considered that. I haven't really worked with the `JSONPath` parts of `aeson` before, so I don't know how they work. Currently, we can get errors like this:

    >>> eitherDecode "{\"hey\": {\"foo\": \"not_number\"}}" :: Either String (M.Map Text (M.Map Text Int))
    Left "Error in $.hey.foo: expected Int, encountered String"

Which is good. If we instead expect an `Int` key, we get:

    >>> eitherDecode "{\"hey\": {\"foo\": \"ht\"}}" :: Either String (M.Map Text (M.Map Int Int))
    Left "Error in $.hey: input does not start with a digit"

What error would we expect instead?

**Comment by phadej** [comment]
@andrewthad @bergmark https://github.com/bos/aeson/pull/423

**Comment by phadej** [comment]
Bikeshedding, should `0.12` be actually `1`. There are so many changes which even are kind-of backwards compatible but not really.

**Comment by andrewthad** [comment]
I actually had the same thought yesterday. Even though the changes in this release probably cause very little breakage, they are some pretty substantial changes. Much bigger than anything that's happened since at least as far back as the `0.6` release. I think calling it a `1.0` release would be appropriate.

**Comment by tolysz** [comment]
The new trend would be to call it `2016.0`

**Comment by bergmark** [comment]
Sure v1 sounds good.

**Comment by andrewthad** [comment]
Just put up some improved docs for `FromJSONKey`: https://github.com/bos/aeson/pull/428

**Comment by phadej** [comment]
tried to port `insert-ordered-containers`: seems to work, yet we have less helpers to building `Value`s then `Encoding`s https://github.com/phadej/insert-ordered-containers/pull/5/files

**Comment by phadej** [comment]
Should https://github.com/bos/aeson/issues/437 be added to the list?

**Comment by phadej** [comment]
Recently added TODOs:

- [ ] `toJSONKeyTextEnc :: (a -> Encoding' Text) -> ToJSONKeyFunction a` (analogue to `toJsonKeyText`) should this be exported?
- [ ] also `toJSONKeyTextEnc`: `dropAround` is also used in `stringEncoding`, which is unfortunate atm. I don't have any idea how fix this without breaking changes. But I don't think it's very important.
- [ ] `Builder.hs`: Extend documentation with references to source code in `blaze-html` or `aeson` that uses this function. @RyanGlScott ?
- [ ] TODOs for https://github.com/bos/aeson/issues/317

**Comment by RyanGlScott** [comment]
@phadej That comment was copied wholesale from `text`, so it wasn't meant to reflect something that actually needed to be done in `aeson`. It can be removed if you desire.

**Comment by phadej** [comment]
*Write tests for lifted typeclasses and their generic/th derivations* is done by #439.

Is there something we can help to make `aeson-1.0.0.0` land on Hackage?

**Comment by bergmark** [comment]
I'm planning to sit down this weekend and see if I can more stuff ready.

* I'm not sure if we should merge #452 before, I'd still like to see benchmarks result and a haskell version of the module. It could be added later but it feels a bit sketchy to hide it in a minor version.
* #424 bothers me, but perhaps putting -O2 under a manual flag is good enough.

**Comment by bergmark** [comment]
@phadej I'm looking at the new `Encoding` modules. `(><)` and `(>*<)` are only exported from the internal module. Are they redundant when writing instances?

**Comment by phadej** [comment]
Yes, they are. They are used to implement high-level combinators.

**Comment by bergmark** [comment]
Does it then make sense to not export those at all and change all instances to only use the public API?

**Comment by phadej** [comment]
@bergmark IIRC template haskell derivation uses them. It can be changes not to use them, but i'm not sure it's worth the effort atm.

**Comment by bergmark** [comment]
A lot of code uses the internals.
```
$ git grep '>\*<' Data/Aeson/Types/ToJSON.hs  | wc -l
     110
```

I imagine that people will look at existing instances for inspiration so it'd be nice to show how the library is supposed to be used there.

**Comment by phadej** [comment]
@bergmark those are the tuples, aren't they?

**Comment by phadej** [comment]
Could be "easily" redone, as code is generated...

**Comment by bergmark** [comment]
yeah i'm working on it

**Comment by winterland1989** [comment]
@bergmark  I can provide benchmark result, just let me know which benchmark you wanna run, i'll try to give it a go. The result for benchmarks in master has already upload in #452 .

**Comment by phadej** [comment]
@bergmark note the `QuickCheck` pull requests. IMHO it makes sense to bump bounds for `aeson-0.11` for now at least.

**Comment by phadej** [comment]
Great, thanks for the release!
